---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mehdb
  annotations:
    statefulsets.kubernetes.io/drainer-pod-template: |
      {
        "metadata": {
          "labels": {
            "app": "mehdb-drainer"
          }
        },
        "spec": {
          "terminationGracePeriodSeconds": 5,
          "containers": [
            {
              "name": "main",
              "image": "busybox",
              "env": [
                {
                  "name": "MEHDB_DATADIR",
                  "value": "/mehdbdata"
                }
              ],
              "command": ["/bin/sh", "-c", "echo \"Datadir '$MEHDB_DATADIR' content now: \" ; find $MEHDB_DATADIR ; echo \"Draining data... this takes 10 seconds!\" ; sleep 10 ; rm -rf $MEHDB_DATADIR/* ; find $MEHDB_DATADIR"],
              "volumeMounts": [
                {
                  "name": "data",
                  "mountPath": "/mehdbdata"
                }
              ]
            }
          ]
        }
      }
spec:
  selector:
    matchLabels:
      app: mehdb
  serviceName: "mehdb"
  replicas: 2
  template:
    metadata:
      labels:
        app: mehdb
    spec:
      containers:
      - name: shard
        image: quay.io/mhausenblas/mehdb:0.6
        ports:
        - containerPort: 9876
        env:
        - name: MEHDB_DATADIR
          value: "/mehdbdata"
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          httpGet:
            path: /status
            port: 9876
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          httpGet:
            path: /status?level=full
            port: 9876
        volumeMounts:
        - name: data
          mountPath: /mehdbdata
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mehdb
  labels:
    app: mehdb
spec:
  ports:
  - port: 9876
  clusterIP: None
  selector:
    app: mehdb
